name: network
description: Network package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  freezed_annotation:
  json_annotation:
  pretty_dio_logger: ^1.3.1
  intl: ^0.19.0
  http_parser: ^4.0.2
  logger: ^1.3.0
  curl_logger_dio_interceptor: ^1.0.0
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner:
  freezed: ^2.3.2
  json_serializable: ^6.6.1